image: docker:latest

services:
  - docker:dind

stages:
  - build

variables:
  DOCKER_IMAGE: lazerbeakravage/chrony-server
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_TLS_CERTDIR: ""

before_script:
  - docker login -u "DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"

build:
  stage: build
  script:
    - docker buildx create --use --name multiarch-builder
    - docker buildx inspect --bootstrap
    - docker buildx build --platform linux/amd64,linux/arm64 -t $DOCKER_IMAGE:latest --push .
