image: docker:latest

services:
  - docker:dind

stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE: lazerbeakravage/chrony-server
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

build:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE:latest .
    - docker tag $DOCKERIMAGE:latest $DOCKER_IMAGE/latest

deploy:
  stage: deploy
  script:
    - docker login -u "DOCKERHUB_USERNAME" -p "$DOCKER_PASSWORD"
    - docker push $DOCKERIMAGE:latest
