stages:
  - build

variables:
  DOCKER_IMAGE: lazerbeakravage/chrony-server

build:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE:latest .
    - echo "DOCKERHUB_TOKEN" | docker login -u "DOCKERHUB_USERNAME" --password-stdin
    - docker push $DOCKERIMAGE:latest