image: docker:latest

services:
  - docker:dind

stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE: lazerbeakravage/chrony-server
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

build:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE:latest .
    - docker tag $DOCKER_IMAGE:latest $DOCKER_IMAGE:latest

deploy:
  stage: deploy
  script:
    - docker login -u "DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"
    - docker push $DOCKER_IMAGE:latest
