default:
  image: docker:latest
  services:
    - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  GHCR_IMAGE: ghcr.io/${GHCR_USERNAME}/chrony-server
  DOCKER_TAG: ${CI_COMMIT_SHA:0:8}
  BUILDX_PLATFORMS: "linux/amd64,linux/arm64"

stages:
  - build_and_push

build_multiarch:
  stage: build_and_push
  tags:
    - docker
  before_script:
    - echo "$GHCR_TOKEN" | docker login ghcr.io -u "$GHCR_USERNAME" --password-stdin
    - docker buildx create --use --name multiarch-builder
    - docker buildx inspect --bootstrap
  script:
    # provenance and sbom are needed to prevent unknown/unknown tags in github
    # https://github.com/orgs/community/discussions/45969#discussioncomment-4852744
    - >
      docker buildx build
      --provenance=false
      --sbom=false
      --platform ${BUILDX_PLATFORMS}
      --tag ${GHCR_IMAGE}:${CI_COMMIT_SHA:0:8}
      --tag ${GHCR_IMAGE}:latest
      --push
      .
