stages:
  - build

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  BUILDX_NO_DEFAULT_ATTESTATIONS: 1

build-multiarch:
  image: docker:latest
  stage: build
  services:
  - docker:dind
  before_script:
    - apk add --no-cache curl git bash
    - docker login ghcr.io -u "$GHCR_USERNAME" -p "$GHCR_TOKEN"
    - docker buildx create --use --name multiarch-builder --driver docker-container
    - docker buildx inspect --bootstrap
  script:
    - docker buildx build --no-cache \
      --push \
      --provenance=false \
      --sbom=false \
      --platform linux/amd64,linux/arm64 
      --tag ghcr.io/lazerbeakravage/telegraf-snmp:latest \
      .