#!/bin/sh

CONF="/etc/chrony/chrony.conf"

echo -e "# Generated by entrypoint.sh\n" > "$CONF"

for NTP in ${NTP_SERVERS:-"pool.ntp.org"}
do
    echo "pool $NTP iburst" >> "$CONF"
done

for SUBNET in ${ALLOWED_CLIENTS:-""}
do
    echo "allow $SUBNET" >> $CONF
done

if [ -n "$DENIED_CLIENTS" ]
then
    for SUBNET in ${DENIED_CLIENTS:-""}
    do
        echo "deny $SUBNET" >> $CONF
    done
fi

cat <<EOF >> "$CONF"
initstepslew 10 $NTP_SERVERS
driftfile /var/lib/chrony/chrony.drift
rtcsync
cmdport ${REMOTE_PORT:-0}
logdir /var/log/chrony
clientloglimit 100
EOF

exec "$@"