services:
  dialga:
    image: lazerbeakravage/chrony-server:latest
    hostname: dialga
    ports:
      - target: 123
        published: 123
        protocol: udp
        mode: host
    environment:
      NTP_SERVERS: '0.pool.ntp.org 1.pool.ntp.org time.cloudflare.com'
      # ALLOWED_CLIENTS: "10.55.10.0/24"
    cap_add:
      - SYS_TIME
