name: Docker multiarch build

on:
  push:
    branches:
      - main
    tags:
      - '*'

env:
  IMAGE_NAME: chrony-server
  BUILDX_PLATFORMS: "linux/amd64,linux/arm64"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
  
    permissions:
      contents: read
      packages: write

    steps:
      - name: Set image base name
        id: vars
        run: echo "ghcr_image_base=ghcr.io/${{ secrets.GHCR_USERNAME }}/${{ env.IMAGE_NAME }}" >> "$GITHUB_OUTPUT"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: GitHub CR login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push multiarch docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ env.BUILDX_PLATFORMS }}
          push: true
          provenance: false
          sbom: false
          tags: |
            ${{ steps.vars.outputs.ghcr_image_base }}:${{ github.sha }}
            ${{ steps.vars.outputs.ghcr_image_base }}/${{ env.IMAGE_NAME }}:latest
