name: Docker multiarch build

on:
  push:
    branches:
      - main
    tags:
      - '*'

env:
  GHCR_IMAGE_BASE: "ghcr.io/${{ secrets.GHCR_USERNAME }}/chrony-server"
  BUILDX_PLATFORMS: "linux/amd64,linux/arm64"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
  
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: GitHub CR login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract short commit SHA
        id: vars
        run: echo "short_sha${GITHUB_SHA::8}" >> "$GITHUB_OUTPUT"

      - name: Build and push multiarch docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ env.BUILDX_PLATFORMS }}
          push: true
          provenance: false
          sbom: false
          tags: |
            ${{ env.GHCR_IMAGE_BASE }}:${{ steps.vars.outputs.short_sha }}
            ${{ env.GHCR_IMAGE_BASE }}:latest
